openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.0
paths:
  /prescriptions:
    get:
      tags:
        - prescriptions
      summary: Get prescription list
      operationId: getPrescriptionList
      parameters:
        - name: filter
          in: query
          description: Filter Prescriptions
          required: true
          schema:
            $ref: '#/components/schemas/PrescriptionRequest'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrescriptionResponse'
    post:
      tags:
        - prescriptions
      summary: Create prescription replacement
      operationId: createReplacement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrescriptionUpdateRequest'
      responses:
        default:
          description: successful operation
  /prescriptions/{prescriptionId}:
    get:
      tags:
        - prescriptions
      summary: Get available filters for prescription
      operationId: getFilters
      parameters:
        - name: prescriptionId
          in: path
          required: true
          description: Prescription ID
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrescriptionReplacementResponse'
  /users:
    get:
      tags:
        - user
      summary: Get user list
      operationId: getUserList
      requestBody:
        description: Filter User
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
components:
  schemas:
    PrescriptionRequest:
      type: object
      properties:
        startDate:
          type: number
        endDate:
          type: number
    PrescriptionResponse:
      type: object
      properties:
        prescriptionId:
          type: number
        prescriptionName:
          type: string
        customer:
          $ref: '#/components/schemas/Customer'
        prescriptionDate:
          type: number
        totalAmount:
          type: number
      required:
        - prescriptionId
        - prescriptionName
        - customer
        - prescriptionDate
        - totalAmount
    PrescriptionUpdateRequest:
      type: object
      properties:
        quantity:
          type: number
        instructions:
          type: string
        alternatives:
          type: array
          items:
            $ref: '#/components/schemas/PrescriptionAlternative'
      required:
        - quantity
        - alternatives
    PrescriptionAlternative:
      type: object
      properties:
        id:
          type: number
        quantity:
          type: number
    PrescriptionReplacementResponse:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        value:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/PrescriptionReplacementResponse'
    Customer:
      type: object
      properties:
        customerId:
          type: number
        name:
          type: string
    UserRequest:
      type: object
      properties:
        email:
          type: string
    UserResponse:
      type: object
      properties:
        userId:
          type: number
        name:
          type: string
        email:
          type: string
        role:
          type: string
