openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.0
paths:
  /prescriptions:
    get:
      tags:
        - prescriptions
      summary: Get prescription list
      operationId: getPrescriptionList
      requestBody:
        description: Filter Prescriptions
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrescriptionRequest'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrescriptionResponse'
  /prescriptions/{prescriptionId}:
    get:
      tags:
        - prescriptions
      summary: Get available filters for prescription
      operationId: getFilters
      parameters:
        - name: prescriptionId
          in: path
          required: true
          description: Prescription ID
          schema:
            type: integer
            format: int64
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrescriptionReplacementResponse'
  /products:
    get:
      tags:
        - products
      summary: Get product list
      operationId: getProductList
      requestBody:
        description: Filter Products
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
  /users:
    get:
      tags:
        - user
      summary: Get user list
      operationId: getUserList
      requestBody:
        description: Filter User
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
components:
  schemas:
    PrescriptionRequest:
      type: object
      properties:
        startDate:
          type: number
        endDate:
          type: number
    PrescriptionResponse:
      type: object
      properties:
        prescriptionId:
          type: number
        prescriptionName:
          type: string
        customer:
          $ref: '#/components/schemas/Customer'
        prescriptionDate:
          type: number
        totalAmount:
          type: number
      required:
        - prescriptionId
        - prescriptionName
        - customer
        - prescriptionDate
        - totalAmount
    PrescriptionReplacementResponse:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        value:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/PrescriptionReplacementResponse'
    Customer:
      type: object
      properties:
        customerId:
          type: number
        name:
          type: string
    ProductRequest:
      type: object
      properties:
        name:
          type: string
        available:
          type: boolean
    ProductResponse:
      type: object
      properties:
        productId:
          type: number
        productName:
          type: string
        available:
          type: boolean
    UserRequest:
      type: object
      properties:
        email:
          type: string
    UserResponse:
      type: object
      properties:
        userId:
          type: number
        name:
          type: string
        email:
          type: string
        role:
          type: string
